### PR TITLE
bit too early for elite emails

### PR DESCRIPTION
**Pull request by S10MC2015**

### CODE REVIEW

**Comment by Sh3llcod3** [comment]
@S10MC2015 Please fix the lint issues.

**Comment by Sh3llcod3** [comment]
@S10MC2015 OK, what I would casually suggest is to spin up your favourite virtualenv, install the latest `flake8` with all the add-ons and everything, then remove all config to do with flake8 locally and run it, should work then. The poetry version for `flake8` is out of date and it needs to be updated sometime.

**Comment by S10MC2015** [comment]
ec645d192ed9c3d5b757d8858dc3f583a7528c6f works locally for me. 

Also I will try flake8 thing if I have time tommorow.

**Comment by thebeanogamer** [comment]
Closed as stale

**Pull request closed without merging**
