### PR TITLE
Auto add reactions to quotes

### PR DESCRIPTION
**Pull request by pwnker**

### CODE REVIEW

**Review by Sh3llcod3 — APPROVED** [review]
I don't see a problem code-wise not sure if @thebeanogamer wants this?

**Comment by thebeanogamer** [comment]
We don't need this. Quotes get a max of about 3 downvotes and the upvotes aren't used for anything. Most people forgot this feature even existed until it was pointed out today.

**Comment by thebeanogamer** [comment]
We should probably reduce the deletion quota back to 5 though, I'm happy to merge that PR

**Comment by pwnker** [comment]
Maybe they would get more downvotes if reactions were auto added as the feature would be used intuitively. With regards to upvotes, they were added here just as a way to "like" a particular quote.

**Comment by Sh3llcod3** [comment]
@pwnker wanted to reopen this yes

**Pull request closed without merging**
