### PR TITLE
Make the Staff Stop Hating Us

### PR DESCRIPTION
**Pull request by kaovd**
I actually have no idea if this will work someone take over

### CODE REVIEW

**Comment by thebeanogamer** [comment]
When implemented this will fix #65

**Comment by Ge0rg3** [comment]
What's the point in this though? This warns the user about pinging the staff, but the ping still goes through as far as I can see. Wouldn't it be better if we got the user to confirm their intent, ie with a reaction/reply?

**Comment by joker314** [comment]
Can bots edit messages?

If yes, I suppose we could have a reaction confirmation thing. But if not, how can we get a user to confirm their intent? Don't we have to delete their message, and so when they decide to keep it, the authorship information will be stripped. (And even if the bot reposts the message and notes who authored it, the user now lacks the ability to delete the message etc., especially when (if) the bot goes offline)

**Comment by Bentechy66** [comment]
> This seems like a good idea @Ge0rg3, I'm just wondering if bots can edit messages?
> 
> If yes, I suppose we could have a reaction confirmation thing. But if not, how can we get a user to confirm their intent? Don't we have to delete their message, and so when they decide to keep it, the authorship information will be stripped. (And even if the bot reposts the message and notes who authored it, the user now lacks the ability to delete the message etc., especially when (if) the bot goes offline)

Bots cannot edit messages; the Discord API provides no way of doing so. Even if it did, if one pings and then edits one's message to remove the ping, the person who was pinged will still get a notification.

One solution would be to have a dummy role which is called "Cyber Discovery Staff", which none of the staff actually have, and make the real staff role non-pingable. Then, when someone pings the dummy role, the bot asks them to confirm their intent and once they do so, temporarily makes the real role pingable and pings it, then disables the pingable feature of the real role. It could also ping staff members individually.

**Comment by AnonGuy** [comment]
I agree with @Bentechy66. Is there anything that you need help with before you attempt this, @kaovd?

**Comment by joker314** [comment]
Of course, there is the issue that this method can only handle one person at a time. If one person confirms, but the other denies, then they will both mention the relevant administrator.

**Comment by thebeanogamer** [comment]
Closed as we've decided to use a system in the style of #64 instead.

**Pull request closed without merging**
