### PR TITLE
fixed cma command lol sorry for breaking it

### PR DESCRIPTION
**Pull request by H4ckerJ4cker**
this can be merged straight away, fixes a borked conflict resolution.

### CODE REVIEW

**Review by Trefonix — APPROVED** [review]

**Review by Sh3llcod3 — APPROVED** [review]

**Comment by thebeanogamer** [comment]
I'm actually quite impressed that you've broken this, it runs fine locally

**Comment by H4ckerJ4cker** [comment]
Yeah, the flake8 seems to be broken? All checks have passed but it failed.

**Comment by thebeanogamer** [comment]
https://gitlab.com/pycqa/flake8/-/issues/588 it seems to be a known but thought resolves issue

**Comment by thebeanogamer** [comment]
I suspect what's tripping it up is the Walrus, but my local Flake8 thinks that is fixed

**Comment by Sh3llcod3** [comment]
I always knew there was something off about the Flake8 Azure uses, there's got to be something wrong with some config option somewhere or such like that, I have encountered this issue with my PRs before as well.

**Comment by H4ckerJ4cker** [comment]
The error does look like it was caused by the Walrus, but it was [patched](https://github.com/PyCQA/pyflakes/pull/457) in 2019. Unless this is a old version of flake8.

**Pull request merged**
