### PR TITLE
WIP: Upgraded the Level command, alongside small tweak to game command.

### PR DESCRIPTION
**Pull request by picapi**
I thought, with a little while to go before Game starts up again, that it may be useful to allow the preexisting level command to be utilised with the new base(s) that are likely to be introduced in the new version. I am submitting this pull request more as a request for feedback at current, however with the intention on creating a fully polished feature. The submitted code functions in a local test, however it is unknown if it will function within the production enviroment, due to difficulties in the configuration of Docker on Windows 10.

Changes:
- Moved the data files used for commands into a new data folder within the bot folder structure.
- Recreated the headquarters.json file as game.json, in order to facilitate all, and new, bases.
    - Format slightly modified, now uses ordered nested lists in order to define challenge number and level number.
- Added a BASE_ALIASES constant, allowing the definition of aliases for each base.
- Upgraded the functionality of the level command, allowing it to be utilised for multiple bases, rather than only HQ.
- Made the game command output a single message, rather than two.

### CODE REVIEW

**Comment by joker314** [comment]
Looks good!

~~Dang it when this is merged it'll conflict with #83~~

**Comment by AnonGuy** [comment]
Looks good to me!

**Comment by fractalpenguin** [comment]
It looks fine, although I'm not sure whether having last year's Game questions is permissible under the Terms and Conditions: https://www.joincyberdiscovery.com/terms. The functionality is fine, but I would be wary of having the questions up now.

**Comment by Bentechy66** [comment]
Also, to further @fractalpenguin's comment about the EULA, this is potentially breaking clause 2.2.3, 2.2.14, 6.11, 12.1, and 12.2. However, last year's `game` command also broke all these clauses and all the official cyber discovery staff didn't seem to have a problem. Perhaps however, contacting CD support and obtaining written permission would be the best thing to do.

**Pull request merged**
