### PR TITLE
Reduce quote deletion quota to 5

### PR DESCRIPTION
**Pull request by thebeanogamer**

### CODE REVIEW

**Review by Sh3llcod3 — APPROVED** [review]

**Review by RealJammy — APPROVED** [review]
its alright

**Review by 404dcd — APPROVED** [review]

**Review by NicholasG04 — CHANGES_REQUESTED** [review]
0/10 no TypeScript.

**Comment by RealJammy** [comment]
> 0/10 no TypeScript.

I'd argue the absence of TypeScript makes it a good PR.

**Review by diogoscf — APPROVED** [review]
Agree with nick on the lack of typescript but looks good otherwise!

**Review by Trefonix — APPROVED** [review]

**Comment by Trefonix** [comment]
beano is cute pass it on

**Pull request merged**
