### PR TITLE
Add Minecraft stat command

### LINKED ISSUE #602: Minecraft Server command
**Is your feature request related to a problem? Please describe.**
I think it would be good if we made an :mcserver or :server command to report on the status of the minecraft server

**Describe the solution you'd like**
Command reports player count, maybe player names, version, up/not up ....

**Describe alternatives you've considered**
There is no alternative

**Additional context**
none required

### PR DESCRIPTION
**Pull request by H4ckerJ4cker**
Closes #602 
Uses a extra module to query mc servers.
http://github.com/Dinnerbone/mcstatus
image

### CODE REVIEW

**Comment by H4ckerJ4cker** [comment]
need to improve title and var names, and add server ip to constants

**Review by thebeanogamer — CHANGES_REQUESTED** [review]
ARGH

**Comment by H4ckerJ4cker** [comment]
just need to optimise a bit more.

**Comment by H4ckerJ4cker** [comment]
ready to be merged

**Review by Sh3llcod3 — APPROVED** [review]

**Comment by Sh3llcod3** [comment]
No idea if this is needed but if it is, then sure?

**Comment by H4ckerJ4cker** [comment]
> No idea if this is needed but if it is, then sure?

someone made an issue so ¯\_(ツ)_/¯

**Comment by david-cooke** [comment]
this is literally useless

**Comment by thebeanogamer** [comment]
And MC is kill

**Comment by H4ckerJ4cker** [comment]
Bro i spent a day on this, im coming to slough and ima git you

**Pull request closed without merging**
