### PR TITLE
A command which returns a random fact

### PR DESCRIPTION
**Pull request by csharpisez**
A command which returns a random fact (using the randfacts package)

### CODE REVIEW

**Comment by thebeanogamer** [comment]
What? Why? No.

**Comment by david-cooke** [comment]
why

**Comment by david-cooke** [comment]
@thebeanogamer @Bentechy66 @AnonGuy thoughts on adding this to ractf backend?

**Comment by Bentechy66** [comment]
@david-cooke I think our users would benefit lots from a "fact of the day" box, how educating!

**Comment by H4ckerJ4cker** [comment]
_I can get behind this fully_. This would be beneficial to any project.

**Pull request closed without merging**
