### PR TITLE
[WIP] Fallback moderation

### PR DESCRIPTION
**Pull request by Sh3llcod3**
__This PR proposes to gradually add in new fall-back moderation features which aim to loosely mirror the ones found in `Dyno`. It is a work in progress that will develop gradually over the following weeks.__

Over the recent few weeks, the server has seen explosive growth and now sits well above 2400 members. Due to increasing member count, the moderation activity and scale of incidents have also increased, which has warranted frequent use of the `Dyno` moderation bot. 

As we are all aware, `Dyno` recently has been suffering a whole host of issues with their back-end causing a 100% outage in all of the non-paid servers it is in. This has made moderation significantly harder as timed mute roles now have to be added and removed by hand. It's made mass-deleting messages in case of a string of bad messages almost impossible. We also don't have the ability to send warnings or maintain mod-logs. This highlights our dependency on `Dyno`.

If we added a basic form of these features into our bot, then we would greatly benefit from having this redundancy. This is where this PR proposes to address these problems by adding in a drop in yet basic replacement for Dyno.

So, why create a PR now and not a proper one a few weeks later when its more developed then just the bare-bones structure? There are some valid reasons for doing so:

- Advantage of Azure CI
- Benefit from extra sets of eyes
- Maintainers have write access, they can edit according to their need
- Allows discussions
- Easier to bring up to date with any changes to master

**Note: This is a duplicate of #261 as I have removed my fork by accident.**

### CODE REVIEW

**Comment by Sh3llcod3** [comment]
@AnonGuy This is the new PR, should I close the previous one?

**Comment by thebeanogamer** [comment]
So setting aside any previous reservations that I may have expressed, I'd like to take this moment to remind you that we already have a Postgres DB running, and we really don't need a seperate SQLite.

**Comment by thebeanogamer** [comment]
And again, I'm not really convinced that this is needed...

**Comment by Sh3llcod3** [comment]
@thebeanogamer As you say, for the DB, I can easily switch this over to the existing Postgres instance and insert the data in a separate table if you wish, that would be a fairly trivial change.

As far as the worth of having such a thing, if this is not required, then I'd be more than happy to close this as well as the other PR and properly rewrite our site (again, but this time utilising `npm`). 

I am not sure if there is a backup bot that can be used a drop-in replacement for `Dyno`. If there is, great. If there isn't, well maybe having something to substitute some of the functionality would be useful. Again, I don't know, but if this isn't required, I'd be happy to close this.

**Comment by Sh3llcod3** [comment]
@thebeanogamer So what is the consensus then? Is this not required?

**Comment by Sh3llcod3** [comment]
I've saved this branch and pushed it to my local git server. For now, it seems as this is not really required, hence I'm closing this PR. If this feature is necessary, give me a shout, and I'll pull the branch and work on this again.

**Pull request closed without merging**
