### PR TITLE
Require Sudo/Root verification for official ping

### PR DESCRIPTION
**Pull request by AnonGuy**
Now that we have plenty of Sudos, and considering the abuse of the ping feature recently, I think it's worth requiring staff verification for official staff pings.

### CODE REVIEW

**Comment by thebeanogamer** [comment]
Has this been tested with people other than an admin clicking the thumbs up button before an admin does?

**Comment by thebeanogamer** [comment]
Also, I'm debating if pinging server staff would be a good idea. Feels like stuff will get missed if not, and people will spam server staff pings to ask for approvals anyway.

**Comment by lightspeedana** [comment]
Looks good, but people may start spamming us with pings in order to verify. At the same time, I don't think there's much else that could be done so unless someone has an alternative, I'm fine with this 🤷‍♀

**Comment by thebeanogamer** [comment]
~Not like Official Staff read their pings anyway~~

**Comment by AnonGuy** [comment]
Any updates on this?

**Comment by thebeanogamer** [comment]
#319 solved this

**Pull request closed without merging**
