### PR TITLE
CyberStart Elite is Kill

### PR DESCRIPTION
**Pull request by thebeanogamer**
image

### CODE REVIEW

**Comment by chop0** [comment]
🦀 elite is gone 🦀

**Comment by Bottersnike** [comment]
image

**Comment by david-cooke** [comment]
:crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab: :crab:

**Review by Sh3llcod3 — APPROVED** [review]
This is great

**Review by jerbob — APPROVED** [review]

**Comment by RealJammy** [comment]
🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀 🦀

**Review by Trefonix — APPROVED** [review]
https://image.shutterstock.com/image-photo/crying-boy-gun-on-coast-260nw-234663073.jpg

**Pull request merged**
