### PR TITLE
Create Soundboard

### PR DESCRIPTION
**Pull request by thebeanogamer**

### CODE REVIEW

**Comment by thebeanogamer** [comment]
When implemented, this will resolve #29

**Comment by thebeanogamer** [comment]
@st1ngr3y @Sh3llcod3 Can I close this, given that nothing has happened on it for months?

**Comment by AnonGuy** [comment]
Closing this branch after a discussion with @Sh3llcod3 - we'll reopen this PR when work starts on it.

**Comment by Sh3llcod3** [comment]
Yep, we'll reopen after it's finished.

**Pull request closed without merging**
