### PR TITLE
Disable Reactions

### PR DESCRIPTION
**Pull request by thebeanogamer**
Disable the reactions system until injection can be fixed.

### CODE REVIEW

**Comment by thebeanogamer** [comment]
@shadycake Please merge and destroy your creation so the bot may return.

**Comment by thebeanogamer** [comment]
@shadycake You said you were going to rewrite the function anyway. Right now, no one uses it, so we may as well just remove it rather than wasting time getting it safe.

**Comment by shadycake** [comment]
Wasting time? https://github.com/CyberDiscovery/cyberdisc-bot/pull/25

**Comment by thebeanogamer** [comment]
This PR has been superseeded by #25

**Pull request closed without merging**
