### PR TITLE
Readme fix

### PR DESCRIPTION
**Pull request by teamshortcut**

### CODE REVIEW

**Comment by Sh3llcod3** [comment]
:eyes:

**Comment by Sh3llcod3** [comment]
Has our CI solution completely broken down at this point?

**Comment by jos-b** [comment]
Considering it just reported as failing I think it works 😃

**Comment by Sh3llcod3** [comment]
@teamshortcut Flake8 has another error, might wan't to fix the massive line in `constants.py` :woman_shrugging:

**Comment by Sh3llcod3** [comment]
*Inb4 build fails.*

**Comment by teamshortcut** [comment]
I wish only for death.

**Comment by Sh3llcod3** [comment]
@teamshortcut Flake8 errors again :man_facepalming:

**Comment by Sh3llcod3** [comment]
@Ge0rg3 Can you delete the stale branch?

**Pull request merged**
