### PR TITLE
Remove :lmgtfy

### PR DESCRIPTION
**Pull request by david-cooke**
the commands literally just spam and also noone uses it except that one skid, theres no point in it existing

### CODE REVIEW

**Comment by RealJammy** [comment]
I approve this

**Review by Sh3llcod3 — APPROVED** [review]
This better contain a 0day to delete the server

**Review by AmusedNetwork — CHANGES_REQUESTED** [review]
Can you also remove the rest of the bot?

**Review by AmusedNetwork — APPROVED** [review]
on second thoughts, just do it

**Comment by H4ckerJ4cker** [comment]
Yep we should yeet it

**Review by H4ckerJ4cker — APPROVED** [review]
Yep remove it

**Comment by thebeanogamer** [comment]
But even Dave uses the command...
image

**Comment by david-cooke** [comment]
@thebeanogamer thats not the command fuckwit

**Comment by 404dcd** [comment]
LGTM

**Comment by thebeanogamer** [comment]
This might be a good idea, but Jack likes it so it's automatically a bad one.

**Pull request closed without merging**
