### PR TITLE
Add the RACTF 2021 dates

### PR DESCRIPTION
**Pull request by thebeanogamer**

### CODE REVIEW

**Review by david-cooke — APPROVED** [review]

**Review by 404dcd — APPROVED** [review]

**Review by jb3 — APPROVED** [review]
:trollface:

**Review by RealJammy — APPROVED** [review]
I approve

**Comment by 404dcd** [comment]
We do a moderate amount of trolling

**Review by Trefonix — APPROVED** [review]

**Review by NicholasG04 — CHANGES_REQUESTED** [review]
Not relevant, please close!

**Pull request merged**
