### PR TITLE
Minimize Dockerfile steps.

### PR DESCRIPTION
**Pull request by jchristgit**
This commit minimizes the amount of steps required to build the Docker image used to run this service. This has two main benefits:

- Reducing initial build time
- Removing intermediate layers

Sent from my iPhone

### CODE REVIEW

**Comment by thebeanogamer** [comment]
This doesn't seem to make any difference to the build time?
With this PR:
image
Without this PR:
image

**Comment by jchristgit** [comment]
that looks like a bug in the CI software you're using, through the intermediate layer creation of docker images in the current setup there is no way that this doesn't speed up initial build time. i will try this myself and report back

**Comment by AnonGuy** [comment]
Hi @jchristgit, Thanks for creating this PR. I'm assuming you're in the Discord, so please send us your tag so @thebeanogamer can add you to Community Developers.

**Comment by thebeanogamer** [comment]
👍 I suspect Azure Devops may not keep intermediate containers, which does seem to defeat half the point of Docker.

**Comment by thebeanogamer** [comment]
> 
> 
> Hi @jchristgit, Thanks for creating this PR. I'm assuming you're in the Discord, so please send us your tag so @thebeanogamer can add you to Community Developers.

This message is accurate until the word `can`

**Comment by thebeanogamer** [comment]
But I will invite to the org if you want.

**Comment by AnonGuy** [comment]
Oh, good shout.

**Review by jerbob — APPROVED** [review]

**Comment by jchristgit** [comment]
Hi @AnonGuy, thanks for the warm welcome. I wasn't aware that there is a chat community but looking forward to join. My tag is `Niko Laus#7857`, I will be stopping by in a bit!

**Comment by AnonGuy** [comment]
That's great to hear @jchristgit! Here's a temporary invite link you can use:
https://discord.gg/Gj9D8v

**Comment by jchristgit** [comment]
Results are in!
```sh
jc@buster:~/Documents/Programming/Git/cyberdisc-bot$ time sudo docker build -t cyberdisc-bot --no-cache . >/dev/null 2>&1
  
real    1m42.673s
user    0m0.042s
sys     0m0.037s
jc@buster:~/Documents/Programming/Git/cyberdisc-bot$ git remote add fork https://github.com/jchristgit/cyberdisc-bot
jc@buster:~/Documents/Programming/Git/cyberdisc-bot$ git fetch fork patch-1
gitremote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
From https://github.com/jchristgit/cyberdisc-bot
 * branch            patch-1    -> FETCH_HEAD
  * [new branch]      patch-1    -> fork/patch-1
jc@buster:~/Documents/Programming/Git/cyberdisc-bot$ git checkout patch-1
Branch 'patch-1' set up to track remote branch 'patch-1' from 'fork'.
Switched to a new branch 'patch-1'
jc@buster:~/Documents/Programming/Git/cyberdisc-bot$ time sudo docker build -t cyberdisc-bot --no-cache . >/dev/null 2>&1

real    1m19.542s
user    0m0.033s
sys     0m0.027s
```

The image was pulled before the first build.

**Comment by thebeanogamer** [comment]
Oh, we never pull the existing build into the environment. Would that help?

**Comment by thebeanogamer** [comment]
That would have to be added to [this](https://github.com/CyberDiscovery/cyberdisc-bot/blob/master/azure-pipelines.yml)

**Comment by jchristgit** [comment]
Do you mean the build cache? My tests use `--no-cache`.

**Comment by thebeanogamer** [comment]
Ah, I see what you mean.

**Comment by thebeanogamer** [comment]
But that still doesn't explain why it takes less time your way, which is interesting...

**Comment by thebeanogamer** [comment]
I'm impressed @jos-b or @AnonGuy haven't showed up to moan about Azure Devops, they normally have by now.

**Comment by thebeanogamer** [comment]
Is it possibly linked to internet speed, as Azure is running from a data centre?

**Comment by thebeanogamer** [comment]
🤷‍♂️ If that's the case, we can still make the change to help people doing local dev.

**Comment by AnonGuy** [comment]
Azure Devops bad

**Comment by thebeanogamer** [comment]
There we go.

**Review by jb3 — APPROVED** [review]
Fantastic PR

**Review by thebeanogamer — APPROVED** [review]

**Comment by jos-b** [comment]
Dear Mr. O’gamer,

It appears you have added a commit to this Pull Request titled "Yay Alphabetical Order".

I’d like to notify you that I take offence at this action. Not only is the English alphabet not used by a large number of countries all over the world, but alphabetic sorting is completely arbitrary. There is no reason why A should come before B, or why Z should come last, who said they must? Do you have a reason? Or have you just been indoctrinated into this dictating regime.

This diagram shows the evolution of the alphabet:

Pasted Graphic

This diagram shows how that the alphabet we use today is derived from the Proto-Sinaitic period, where characters were mere pictures. You will notice how the order has changed throughout the years. This proves that the alphabet we use today has no logical sorting and by alphabetically sorting items you are just placing them into another random order, and in turn you are putting your grubby mitts over the git history of this PR.

I’d therefore like to ask you to refrain from ever alphabetically sorting code ever again and to revert the commit from the repository, thank you.

**Comment by jos-b** [comment]
hi guys any progress on this?

**Comment by jerbob** [comment]
hi guys any progress on this?

**Comment by jb3** [comment]
hi guys any progress on this?

**Pull request merged**
