### PR TITLE
[WIP] Gradually add fallback moderation features

### PR DESCRIPTION
**Pull request by Sh3llcod3**
__This PR proposes to gradually add in new fall-back moderation features which aim to loosely mirror the ones found in `Dyno`. It is a work in progress that will develop gradually over the following weeks.__

Over the recent few weeks, the server has seen explosive growth and now sits well above 2400 members. Due to increasing member count, the moderation activity and scale of incidents have also increased, which has warranted frequent use of the `Dyno` moderation bot. 

As we are all aware, `Dyno` recently has been suffering a whole host of issues with their back-end causing a 100% outage in all of the non-paid servers it is in. This has made moderation significantly harder as timed mute roles now have to be added and removed by hand. It's made mass-deleting messages in case of a string of bad messages almost impossible. We also don't have the ability to send warnings or maintain mod-logs. This highlights our dependency on `Dyno`.

If we added a basic form of these features into our bot, then we would greatly benefit from having this redundancy. This is where this PR proposes to address these problems by adding in a drop in yet basic replacement for Dyno.

So, why create a PR now and not a proper one a few weeks later when its more developed then just the bare-bones structure? There are some valid reasons for doing so:

- Advantage of Azure CI
- Benefit from extra sets of eyes
- Maintainers have write access, they can edit according to their need
- Allows discussions
- Easier to bring up to date with any changes to master

### CODE REVIEW

**Comment by AnonGuy** [comment]
It might be worth marking this PR as WIP

**Comment by Sh3llcod3** [comment]
> It might be worth marking this PR as WIP

~~You're right but Hacktoberfest is a thing~~ :smile:

**Comment by AnonGuy** [comment]
> > It might be worth marking this PR as WIP
> 
> ~You're right but Hacktoberfest is a thing~ smile

Marking this as WIP shouldn't invalidate the PR

**Comment by Sh3llcod3** [comment]
> Marking this as WIP shouldn't invalidate the PR
Ok, let's do that.

**Comment by Sh3llcod3** [comment]
@AnonGuy Hey, so I've made another branch with these changes, this is a duplicate PR, should this be closed or is there a way to bring the `fallback_moderation` branch to this PR. I've also removed my fork, which is why it says `Unknown Repository`.

**Pull request closed without merging**
