### PR TITLE
Jump to message log

### PR DESCRIPTION
**Pull request by jos-b**
Adds another field to the error embed which allows a message to be jumped to if the error occurred in a server.

### CODE REVIEW

**Comment by jos-b** [comment]
you can't approve when it failed lint that's agains the law

**Comment by jos-b** [comment]
beans there were so many mistakes with that previous commit I'm worried that you approved that...

**Comment by AnonGuy** [comment]
image

**Comment by jos-b** [comment]
than k

**Comment by jos-b** [comment]
Jump 🆙 to :two: message 📥 logs 🌲

**Pull request merged**
