### PR TITLE
Added :cma Command

### PR DESCRIPTION
**Pull request by H4ckerJ4cker**
All the other bots must die. This counts right? ITS HACKTOBERFEST BABY.

### CODE REVIEW

**Comment by KyokoKirigiri11037** [comment]
is this what defrauding digitalocean looks like?

**Comment by david-cooke** [comment]
why

**Review by thebeanogamer — CHANGES_REQUESTED** [review]
This is not what `?cma` does, that one returns images of the various sections

**Comment by david-cooke** [comment]
To clarify, "why" is the official response of the cd server, I'm doing code review on behalf of beano

**Comment by RealJammy** [comment]
This seems like a spammy request to get a hacktoberfest PR.

**Review by Sh3llcod3 — APPROVED** [review]

**Review by Sh3llcod3 — COMMENTED** [review]
I am approving provisionally, I am not sure if this is what is needed.

**Comment by H4ckerJ4cker** [comment]
image
This should be pretty much the same functionality as the dyno commands just slightly better.

**Review by thebeanogamer — CHANGES_REQUESTED** [review]
The current version also covers 3a and 3za

**Review by thebeanogamer — APPROVED** [review]
God I can't wait for Python 3.10 and switch-case

**Pull request merged**
