### PR TITLE
Integrate Both Maths Bots

### LINKED ISSUE #375: Merge Maths Challenge Bot
https://github.com/teamshortcut/Discord-Maths-Bot

We should merge this bot into CDbot to reduce the number of bots we are running

### LINKED ISSUE #377: Maths Rendering
Currently we use https://github.com/DXsmiley/mathbot for maths rendering. This should be migrated into CDbot so we can remove the bot.

### PR DESCRIPTION
**Pull request by thebeanogamer**
Resolves #377 
Resolves #375

### CODE REVIEW

**Comment by thebeanogamer** [comment]
Must remember to add automation to the new maths cog

**Comment by AnonGuy** [comment]
I'm assuming you've tested the LaTeX stuff?

**Comment by AnonGuy** [comment]
Ah yes I forgot WIP PRs are a thing now

**Comment by thebeanogamer** [comment]
https://github.com/CyberDiscovery/cyberdisc-bot/blob/13c743644abb5252c838067402cf91f2202ca86f/poetry.lock#L69-L75

What is adding this?

**Comment by thebeanogamer** [comment]
image
Returning embeds from functions is funky and I'm too tired to fix it

**Comment by ZomBMage** [comment]
What you need to do is run to_dict on the variable on the next line
Asyncio doesn't work like the above problem

**Pull request merged**
