### PR TITLE
Change wand to Pillow

### PR DESCRIPTION
**Pull request by justanotherfailure**
Pillow is better than wand because imagemagick is bad

### CODE REVIEW

**Comment by thebeanogamer** [comment]
@justanotherfailure Have you been able to test this? Please post some GIFs showing it works.

**Comment by justanotherfailure** [comment]
<div style="width:100%;height:0px;position:relative;padding-bottom:56.250%;"><iframe src="https://streamable.com/s/lmlvw/usosjj" frameborder="0" width="100%" height="100%" allowfullscreen style="width:100%;height:100%;position:absolute;left:0px;top:0px;overflow:hidden;"></iframe></div>

**Comment by thebeanogamer** [comment]
All of the long strings you used there work on the existing implementation. Will this version make the text smaller to fit the box?

**Comment by justanotherfailure** [comment]
I could add that, but the main purpose of this PR was to replace wand with pillow (because ImageMagick is bad.)

**Comment by thebeanogamer** [comment]
How long would that actually take to implement?

**Comment by thebeanogamer** [comment]
But yes, I agree, Imagemagick bad

**Comment by justanotherfailure** [comment]
I'll take a look and get back to you :+1:

**Comment by justanotherfailure** [comment]
nvm me saying not very long, taking a look at the things i'd need to change it'd be very long due to the centralisation being dependent on the font size remaining the same, the changing of it leading to miscentralisation.

I'll try looking for a not long way of doing this

**Comment by thebeanogamer** [comment]
🤷‍♂️ Maybe something to look at down the line

**Pull request merged**
