### PR TITLE
Hopefully fixes lint bug

### LINKED ISSUE #569: flake8 linter can't handle Walrus operator
**Describe the bug**
flake8 linter can't handle Walrus operator.

**To Reproduce**
1. Run checks on code with the Walrus operator.
2. See error `"pyflakes" failed during execution due to "'FlakesChecker' object has no attribute 'NAMEDEXPR'"`
3. Lint fails.

**Expected behavior**
Pass the lint check.

**Additional context**
I suspect this is caused by an out of date version of flake8.

### PR DESCRIPTION
**Pull request by H4ckerJ4cker**
I think this will update all the flake8 modules to the latest. This needs properly checked before it's merged. maybe resolves #569

### CODE REVIEW

**Comment by thebeanogamer** [comment]
Ohhhhhhhh, yeah, that'll do it

**Review by thebeanogamer — APPROVED** [review]

**Comment by thebeanogamer** [comment]
We really should EoL the requirements txt

**Comment by H4ckerJ4cker** [comment]
@thebeanogamer in this file however there is no set version for Pyflake, I assume though it will be updated as part of the main flake8.

**Review by Sh3llcod3 — APPROVED** [review]
For my next trick, I will EoL the bot

**Pull request merged**
