### PR TITLE
Semaphore setup

### LINKED ISSUE #167: Moving to a new CI platform
We've already had some internal discussion on possible CI platforms that we can use, but I'm making this issue so we can get some public discussion.

After [Travis' recent acquisition and layoffs](https://news.ycombinator.com/item?id=18978251), some of our bot contributors have expressed concerns on whether continuing to use the service is a safe bet. For that reason, we're considering a move to a different CI platform. Some solutions we've discussed are:

* **[Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/)**
* **[Circle CI](https://circleci.com/)**

Some things we need to do to complete the migration:
- [ ] Choose a platform
- [ ] Make a PR for the move
- [ ] Create the configuration file/s
- [ ] Ensure @swedg has access to the service and has added the required environment variables

### PR DESCRIPTION
**Pull request by fractalpenguin**
An alternative CI to Azure.

Closes #167 and #158 if merged.

### CODE REVIEW

**Comment by jos-b** [comment]
Aren't we decided on Azure? We've got everything setup now and I've never even heard of Semaphore.

**Comment by jos-b** [comment]
Semaphore also doesn't appear to be free? (yet?)
image

**Comment by thebeanogamer** [comment]
Much though I do appreciate the effort, I honestly can't see any argument for using this, especially with what @jos-b pointed out.

**Comment by Sh3llcod3** [comment]
Dank memes in prod

**Comment by fractalpenguin** [comment]
@jos-b Given the "debate" on azure, and the fact it has not been merged yet, I just wanted to put an alternative forward. Also, there is free credit given. Azure is probably a better alternative though.

**Comment by thebeanogamer** [comment]
We have made the decision to use Azure Devops, which was implemented in #158

**Pull request closed without merging**
