### PR TITLE
Added l33tify

### PR DESCRIPTION
**Pull request by Thomas-Wigley**

### CODE REVIEW

**Comment by Sh3llcod3** [comment]
I'm not sure if this is a required feature, so I'll let @thebeanogamer decide, but its failing the checks can you address them and fix the failing Azure checks mainly?

**Comment by Thomas-Wigley** [comment]
Fixed the style issues, hopefully.

**Comment by thebeanogamer** [comment]
I'm really not sure this is needed...

**Comment by Thomas-Wigley** [comment]
I can assure you it is.

**Comment by thebeanogamer** [comment]
I'm really not convinced that this is needed, I can't say I've seen any users complain of its absence other than the ones you told to DM me.

**Pull request closed without merging**
