### PR TITLE
Tidy Sentry Tags

### PR DESCRIPTION
**Pull request by thebeanogamer**

### CODE REVIEW

**Comment by thebeanogamer** [comment]
This doesn't seem to work as a workaround, will need to be raised with Sentry support. 

<https://sentry.io/organizations/cyber-discovery-community/issues/1560372719/>

**Comment by thebeanogamer** [comment]
```py
scope.set_context("client_os", {"name": system(), "version": release()})
```

The above works, I have opened a Sentry ticket for the Python issues

**Comment by Sh3llcod3** [comment]
:thinking:

**Comment by Sh3llcod3** [comment]
Does lint need to be fixed?

**Comment by thebeanogamer** [comment]
@AnonGuy

**Pull request merged**
