### PR TITLE
Flow chart command

### PR DESCRIPTION
**Pull request by 404dcd**
I designed a better version of Day's flowchart, and have added it as a command.

### CODE REVIEW

**Comment by H4ckerJ4cker** [comment]
IT'S HACKTOBERFEST BABY!

**Review by H4ckerJ4cker — APPROVED** [review]
Looks good to me.

**Review by Sh3llcod3 — APPROVED** [review]
🤔

**Comment by KyokoKirigiri11037** [comment]
beano-san if you could please approve this urgently we would appreciate you for doing your job _for once_

**Review by Trefonix — APPROVED** [review]
fffffffffffffffffiiiiiiiiiiiiiiiiiiinnnnnnnnnnnnnnnnneeeeeeeeeeeeee

**Review by thebeanogamer — APPROVED** [review]
This is junk but oh well

**Pull request merged**
