### PR TITLE
Added voting.py with one poll command

### PR DESCRIPTION
**Pull request by thebeanogamer**
I have no idea if this works, but @shadycake appears to have put in far too much for me to just delete it.

### CODE REVIEW

**Comment by Ge0rg3** [comment]
@thebeanogamer can u deal with this?

**Comment by thebeanogamer** [comment]
I thought we had abandoned this?

**Comment by AnonGuy** [comment]
It's been months without a commit related to this PR. Would @shadycake be opposed to closing this PR and opening an issue for it instead?

**Comment by AnonGuy** [comment]
Yeah, I think I'll close this PR for now, and add an issue. If anyone wants to continue work on this, they can just open a new PR for the `voting-system`  branch.

**Pull request closed without merging**
