### PR TITLE
Alllow voting off of quotes created prior to a bot restart

### PR DESCRIPTION
**Pull request by fractalpenguin**
Solves #353 by using on_raw_reaction_add rather than on_reaction_add, since the former is not dependent on the internal cache.

Turns out you cannot change a PR to a draft one, so the previous PR has been closed.

### CODE REVIEW

**Comment by thebeanogamer** [comment]
Will this work if it's made to pass tests?

**Comment by thebeanogamer** [comment]
Labelling is failing because of when this fork was created, it will be bypassed when this is merged.

**Comment by Sh3llcod3** [comment]
*The ghost linter strikes again?*

**Comment by thebeanogamer** [comment]
Merging with failing PR label is fine

**Comment by Sh3llcod3** [comment]
PR author: *Hopefully this should work*
Linter: *Not so fast*

**Pull request merged**
