### PR TITLE
Added *ALL* of the custom commands.

### PR DESCRIPTION
**Pull request by pwnker**
Some commands are hidden from the help command. Let me know if you to change that in one or all commands. Role commands are not part of this as they are done in my rank command pr #587 . As always lmk of any improvements or optimisations.

### CODE REVIEW

**Review by Sh3llcod3 — APPROVED** [review]
I have no idea if this is needed or not, but sure, I guess. jacc

**Comment by H4ckerJ4cker** [comment]
> I have no idea if this is needed or not, but sure, I guess. jacc

not really needed but it does mean that all the fun and response commands have the same prefix.

**Comment by Sh3llcod3** [comment]
jacc-o-boy

**Comment by H4ckerJ4cker** [comment]
Also I moved like 5 things over and it was merged before I found out there were wayyy more. No point doing half a job.

**Review by Sh3llcod3 — APPROVED** [review]

**Review by Sh3llcod3 — APPROVED** [review]

**Review by thebeanogamer — APPROVED** [review]
Now will you stop asking

**Pull request merged**
