### PR TITLE
Don't run the regex on bot messages

### PR DESCRIPTION
**Pull request by thebeanogamer**

### CODE REVIEW

**Review by RealJammy — APPROVED** [review]
tbh why wasn't this done before

**Review by david-cooke — CHANGES_REQUESTED** [review]
please delete the bot

**Review by Alpheeexx — APPROVED** [review]
LGTM!

**Review by pwnker — APPROVED** [review]

**Review by AdamBromiley — APPROVED** [review]

**Review by jerbob — APPROVED** [review]
image

**Comment by picapi** [comment]
Looks good to me!

**Pull request merged**
