### PR TITLE
Suppress some errors

### PR DESCRIPTION
**Pull request by jos-b**
This adds some code so that errors which don't need reporting are not reported, but are instead given feedback from the bot in the channel at time of execution.

This surpasses:
- Command not found

Provides feedback and suppression for:
- Missing required arguments
- Check failures
- Cooldowns

Adds feedback but does not suppress:
- Argument parsing errors
- Bad argument errors
- All other exceptions

### CODE REVIEW

**Comment by thebeanogamer** [comment]
Will this affect Sentry and Google Stackdriver or just `#developer-log`?

**Comment by jos-b** [comment]
Do they work by adding logging handlers or are they exception-hooks based?

**Comment by thebeanogamer** [comment]
I think:tm: Sentry is a logging handler and Stackdriver is exception based.

**Comment by thebeanogamer** [comment]
But I'd check that

**Comment by jos-b** [comment]
I don't see the issue with suppressing any of the human error things from Sentry anyway

**Comment by jos-b** [comment]
We should be trying to find code errors, not typos and wrong argument usage.

**Comment by jos-b** [comment]
I can't even find any code referencing google stack driver, where is it used?

**Comment by thebeanogamer** [comment]
No, it's not an issue at all. Anything to reduce my email spam is a good thing, and I'll be going through some of the common errors at some point to add validation.

**Comment by thebeanogamer** [comment]
Stackdriver is added by Google Kubernetes Engine, although #202 will improve its output.

**Comment by thebeanogamer** [comment]
Send me an email if you want access to it, I have to add you to the Cloud Console.

**Comment by jos-b** [comment]
From what I can tell both do use logging handlers, so the errors where I've removed the logging will mean the exceptions go from both solutions. Not a hard thing to change, it's as simple as removing a `return`. It's up to you whether we need to keep in the CommandNotFound & Check failures etc.

**Comment by thebeanogamer** [comment]
If you're suppressing it from the log, ideally it would be surpressed from Sentry and Stackdriver as well.

**Comment by jos-b** [comment]
[Stackdriver docs only reference a logging handler](https://cloud.google.com/logging/docs/setup/python#installing_the_library) but Sentry's new SDK makes it unclear how everything works.

**Comment by jos-b** [comment]
The old Sentry SDK (raven) made you use logging handlers but looking [here](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/hub.py) it looks like exception hooks are used instead.

**Comment by jos-b** [comment]
Though [here](https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/logging.py) it looks like the implementation is logging. No clear documentation from Sentry on this one.

**Comment by thebeanogamer** [comment]
Urgh, is it going to request a review from both members of the team?

**Comment by thebeanogamer** [comment]
Oh no, it just needs me to review again because the team wasn't working when I reviewed it the first time.

**Comment by jos-b** [comment]
Yeah, it requires an approving review from at least one member of the team AIUI.

**Comment by jos-b** [comment]
Error

**Pull request merged**
