### PR TITLE
Updated quotes deletion

### LINKED ISSUE #511: Quotes borked pls fix
I'm sure you already know this but quotes aren't getting deleted if they have 10 or more downvotes. I'm going to try to fix this but in the meantime could a mod please moderate and delete these 10 or so messages? Cheers x

https://discord.com/channels/409851296116375565/463657120441696256/735923474710790295
https://discord.com/channels/409851296116375565/463657120441696256/736356554512793613
https://discord.com/channels/409851296116375565/463657120441696256/738068849483710585
https://discord.com/channels/409851296116375565/463657120441696256/738335433875783751
https://discord.com/channels/409851296116375565/463657120441696256/739439081435431002
https://discord.com/channels/409851296116375565/463657120441696256/739605026795683912
https://discord.com/channels/409851296116375565/463657120441696256/739776369319346256
https://discord.com/channels/409851296116375565/463657120441696256/739844938942120047
https://discord.com/channels/409851296116375565/463657120441696256/739961021187489914
https://discord.com/channels/409851296116375565/463657120441696256/735072879259156493

### LINKED ISSUE #518: Quotes don't delete
This happens when you try and delete quotes

image

### PR DESCRIPTION
**Pull request by 404dcd**
When the bot made an embed to send to logs, it tries to mention the users who requested deletion. This failed. `str.join` is now given an iterable, fixes #511 fixes #518

### CODE REVIEW

**Review by AnonGuy — APPROVED** [review]

**Review by thebeanogamer — CHANGES_REQUESTED** [review]
So whilst this does resolve the issue, quotes do delete, it does now hit an exception with the logging if the message doesn't have an embed.
```py
  File ...\cyberdisc-bot\cdbot\cogs\fun.py", line 273, in on_raw_reaction_add
    await logs_channel.send(embed=embed)
UnboundLocalError: local variable 'embed' referenced before assignment
```
We should really have caught this before the code was merged, PyLance points out that this error is possible, so it's our fault that it got into the source.
```py
"embed" is possibly unbound - Pylance (reportUnboundVariable)
```
The `for` loop only makes sense if you assume that every message will have an embed, and even then the log is basically useless.
image
After deleting this message.
image
Whilst we can merge this and have it work, I'd rather fix this entire thing at once.

**Review by thebeanogamer — CHANGES_REQUESTED** [review]
😢  This is how an embed shows up
image
And a user message causes
```py
Traceback (most recent call last):
  File "xxx\cyberdisc-bot\cdbot\cogs\fun.py", line 278, in on_raw_reaction_add
    embed.set_author(name=quote_auth.name, icon_url=quote_auth.icon_url)
AttributeError: 'Member' object has no attribute 'icon_url'
```

**Comment by 404dcd** [comment]
image
Ok, I don't know why this is happening right now. On my testing server I've used UnbelievaBoat quotes and it logs them fine, see attached.
I've got to go to school now, but I reckon I can fix it this evening.

**Comment by 404dcd** [comment]
@thebeanogamer I think the reason why you couldn't delete that embed is because it wasn't a quote - UnbelievaBoat quotes are embeds with a description field (which delete), and I don't think the bot's on_ready message doesn't seem to have a description.

**Review by thebeanogamer — APPROVED** [review]
I've made a few small tweaks, but I'm happy this now works as it needs to.

**Pull request merged**
