### PR TITLE
Update admin.py with purge_from command.

### PR DESCRIPTION
**Pull request by SolitudalDeveloper**
Added purge_from command. Purges messages after a certain ID

### CODE REVIEW

**Comment by thebeanogamer** [comment]
This is way too dangerous to ever be somthing that I'd allow near the bot

**Comment by thebeanogamer** [comment]
I also have no idea who @SolitudalDeveloper is

**Comment by SolitudalDeveloper** [comment]
@thebeanogamer fair enough, I just created it in response to an issue

**Comment by Ge0rg3** [comment]
@thebeanogamer doesn't Dyno already do this?

**Comment by SolitudalDeveloper** [comment]
> 
> 
> @thebeanogamer doesn't Dyno already do this?

Not specifically. It has purge commands, but not one that takes a message ID, and purges all messages since that message.

**Comment by AnonGuy** [comment]
It's been almost a month, and none of the build checks have been solved. I think it's safe to close this PR and open an issue for the suggested command.

**Pull request closed without merging**
